### ISSUE TITLE
AttributeError: 'LossHistory' object has no attribute 'losses'

### ISSUE THREAD

**Issue by liguangzi** [LZQthePlane/Online-Realtime-Action-Recognition-based-on-OpenPose#11]
When I downloaded your file and decompressed it, I wanted to retrain the model, open train.py, change the phrase # model.save ('zyhframewise_recognition.h5') to model.save ('zyhframewise_recognition.h5'), and run train.py.
Error occurred:

C:\ProgramData\Anaconda3\pythonw.exe H:/Online-Realtime-Action-Recognition-based-on-OpenPose-master/Online-Realtime-Action-Recognition-based-on-OpenPose-master/Action/training/train.py
Using TensorFlow backend.
Train on 2960 samples, validate on 329 samples
Epoch 1/20
2019-03-20 17:55:58.365067: I T:\src\github\tensorflow\tensorflow\core\platform\cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2

  32/2960 [..............................] - ETA: 2:03 - loss: 1.2098 - acc: 0.3438
 768/2960 [======>.......................] - ETA: 3s - loss: 1.1682 - acc: 0.4544  
1344/2960 [============>.................] - ETA: 1s - loss: 1.0412 - acc: 0.5417
1952/2960 [==================>...........] - ETA: 0s - loss: 0.9448 - acc: 0.6071
2592/2960 [=========================>....] - ETA: 0s - loss: 0.8621 - acc: 0.6655
2912/2960 [============================>.] - ETA: 0s - loss: 0.8351 - acc: 0.6854
2960/2960 [==============================] - 2s 575us/step - loss: 0.8304 - acc: 0.6892 - val_loss: 0.5008 - val_acc: 0.8906
Epoch 2/20

  32/2960 [..............................] - ETA: 0s - loss: 0.5474 - acc: 0.9375
 544/2960 [====>.........................] - ETA: 0s - loss: 0.5454 - acc: 0.8750
 928/2960 [========>.....................] - ETA: 0s - loss: 0.5366 - acc: 0.8804
1280/2960 [===========>..................] - ETA: 0s - loss: 0.5164 - acc: 0.8867
1760/2960 [================>.............] - ETA: 0s - loss: 0.4962 - acc: 0.8949
2144/2960 [====================>.........] - ETA: 0s - loss: 0.4804 - acc: 0.9002
2592/2960 [=========================>....] - ETA: 0s - loss: 0.4697 - acc: 0.9028
2960/2960 [==============================] - 0s 133us/step - loss: 0.4642 - acc: 0.9037 - val_loss: 0.3654 - val_acc: 0.9210
Epoch 3/20

  32/2960 [..............................] - ETA: 0s - loss: 0.4151 - acc: 0.8750
 544/2960 [====>.........................] - ETA: 0s - loss: 0.3649 - acc: 0.9412
1024/2960 [=========>....................] - ETA: 0s - loss: 0.3741 - acc: 0.9316
1312/2960 [============>.................] - ETA: 0s - loss: 0.3776 - acc: 0.9291
1632/2960 [===============>..............] - ETA: 0s - loss: 0.3729 - acc: 0.9295
1920/2960 [==================>...........] - ETA: 0s - loss: 0.3680 - acc: 0.9297
2336/2960 [======================>.......] - ETA: 0s - loss: 0.3640 - acc: 0.9315
2720/2960 [==========================>...] - ETA: 0s - loss: 0.3657 - acc: 0.9298
2960/2960 [==============================] - 0s 145us/step - loss: 0.3641 - acc: 0.9304 - val_loss: 0.2952 - val_acc: 0.9544
Epoch 4/20

  32/2960 [..............................] - ETA: 0s - loss: 0.3248 - acc: 0.9062
 480/2960 [===>..........................] - ETA: 0s - loss: 0.3031 - acc: 0.9521
 960/2960 [========>.....................] - ETA: 0s - loss: 0.2900 - acc: 0.9573
1376/2960 [============>.................] - ETA: 0s - loss: 0.2961 - acc: 0.9520
1696/2960 [================>.............] - ETA: 0s - loss: 0.2931 - acc: 0.9522
2176/2960 [=====================>........] - ETA: 0s - loss: 0.2929 - acc: 0.9508
2816/2960 [===========================>..] - ETA: 0s - loss: 0.2826 - acc: 0.9528
2960/2960 [==============================] - 0s 111us/step - loss: 0.2899 - acc: 0.9490 - val_loss: 0.2277 - val_acc: 0.9696
Epoch 5/20

  32/2960 [..............................] - ETA: 0s - loss: 0.1878 - acc: 0.9688
 576/2960 [====>.........................] - ETA: 0s - loss: 0.2421 - acc: 0.9635
1056/2960 [=========>....................] - ETA: 0s - loss: 0.2417 - acc: 0.9602
1440/2960 [=============>................] - ETA: 0s - loss: 0.2466 - acc: 0.9563
2016/2960 [===================>..........] - ETA: 0s - loss: 0.2360 - acc: 0.9608
2656/2960 [=========================>....] - ETA: 0s - loss: 0.2243 - acc: 0.9646
2960/2960 [==============================] - 0s 104us/step - loss: 0.2252 - acc: 0.9659 - val_loss: 0.1825 - val_acc: 0.9696
Epoch 6/20

  32/2960 [..............................] - ETA: 0s - loss: 0.1284 - acc: 1.0000
 608/2960 [=====>........................] - ETA: 0s - loss: 0.1948 - acc: 0.9803
1216/2960 [===========>..................] - ETA: 0s - loss: 0.1889 - acc: 0.9811
1888/2960 [==================>...........] - ETA: 0s - loss: 0.1986 - acc: 0.9740
2528/2960 [========================>.....] - ETA: 0s - loss: 0.1925 - acc: 0.9735
2960/2960 [==============================] - 0s 91us/step - loss: 0.1917 - acc: 0.9713 - val_loss: 0.1518 - val_acc: 0.9696
Epoch 7/20

  32/2960 [..............................] - ETA: 0s - loss: 0.1956 - acc: 0.9688
 608/2960 [=====>........................] - ETA: 0s - loss: 0.1691 - acc: 0.9803
1216/2960 [===========>..................] - ETA: 0s - loss: 0.1670 - acc: 0.9786
1824/2960 [=================>............] - ETA: 0s - loss: 0.1634 - acc: 0.9753
2208/2960 [=====================>........] - ETA: 0s - loss: 0.1652 - acc: 0.9760
2752/2960 [==========================>...] - ETA: 0s - loss: 0.1648 - acc: 0.9760
2960/2960 [==============================] - 0s 102us/step - loss: 0.1629 - acc: 0.9770 - val_loss: 0.1257 - val_acc: 0.9726
Epoch 8/20

  32/2960 [..............................] - ETA: 0s - loss: 0.0994 - acc: 1.0000
 640/2960 [=====>........................] - ETA: 0s - loss: 0.1458 - acc: 0.9859
1120/2960 [==========>...................] - ETA: 0s - loss: 0.1404 - acc: 0.9866
1536/2960 [==============>...............] - ETA: 0s - loss: 0.1369 - acc: 0.9857
1792/2960 [=================>............] - ETA: 0s - loss: 0.1376 - acc: 0.9833
2208/2960 [=====================>........] - ETA: 0s - loss: 0.1381 - acc: 0.9823
2688/2960 [==========================>...] - ETA: 0s - loss: 0.1361 - acc: 0.9829
2960/2960 [==============================] - 0s 127us/step - loss: 0.1367 - acc: 0.9824 - val_loss: 0.1088 - val_acc: 0.9787
Epoch 9/20

  32/2960 [..............................] - ETA: 0s - loss: 0.0539 - acc: 1.0000
 480/2960 [===>..........................] - ETA: 0s - loss: 0.1378 - acc: 0.9812
 768/2960 [======>.......................] - ETA: 0s - loss: 0.1311 - acc: 0.9857
1152/2960 [==========>...................] - ETA: 0s - loss: 0.1270 - acc: 0.9844
1856/2960 [=================>............] - ETA: 0s - loss: 0.1259 - acc: 0.9833
2336/2960 [======================>.......] - ETA: 0s - loss: 0.1287 - acc: 0.9824
2624/2960 [=========================>....] - ETA: 0s - loss: 0.1289 - acc: 0.9832
2960/2960 [==============================] - 0s 136us/step - loss: 0.1302 - acc: 0.9824 - val_loss: 0.0963 - val_acc: 0.9757
Epoch 10/20

  32/2960 [..............................] - ETA: 0s - loss: 0.2233 - acc: 0.9062
 544/2960 [====>.........................] - ETA: 0s - loss: 0.1215 - acc: 0.9688
 960/2960 [========>.....................] - ETA: 0s - loss: 0.1116 - acc: 0.9750
1376/2960 [============>.................] - ETA: 0s - loss: 0.1100 - acc: 0.9767
1856/2960 [=================>............] - ETA: 0s - loss: 0.1103 - acc: 0.9784
2400/2960 [=======================>......] - ETA: 0s - loss: 0.1096 - acc: 0.9788
2960/2960 [==============================] - 0s 114us/step - loss: 0.1077 - acc: 0.9807 - val_loss: 0.0857 - val_acc: 0.9818
Epoch 11/20

  32/2960 [..............................] - ETA: 0s - loss: 0.1307 - acc: 0.9688
 448/2960 [===>..........................] - ETA: 0s - loss: 0.1064 - acc: 0.9754
 896/2960 [========>.....................] - ETA: 0s - loss: 0.1025 - acc: 0.9799
1472/2960 [=============>................] - ETA: 0s - loss: 0.0977 - acc: 0.9837
2048/2960 [===================>..........] - ETA: 0s - loss: 0.1011 - acc: 0.9829
2496/2960 [========================>.....] - ETA: 0s - loss: 0.0992 - acc: 0.9844
2816/2960 [===========================>..] - ETA: 0s - loss: 0.0995 - acc: 0.9847
2960/2960 [==============================] - 0s 116us/step - loss: 0.0990 - acc: 0.9851 - val_loss: 0.0792 - val_acc: 0.9878
Epoch 12/20

  32/2960 [..............................] - ETA: 0s - loss: 0.0712 - acc: 1.0000
 608/2960 [=====>........................] - ETA: 0s - loss: 0.1006 - acc: 0.9836
1024/2960 [=========>....................] - ETA: 0s - loss: 0.0955 - acc: 0.9854
1472/2960 [=============>................] - ETA: 0s - loss: 0.0891 - acc: 0.9878
2016/2960 [===================>..........] - ETA: 0s - loss: 0.0876 - acc: 0.9876
2592/2960 [=========================>....] - ETA: 0s - loss: 0.0916 - acc: 0.9857
2960/2960 [==============================] - 0s 103us/step - loss: 0.0911 - acc: 0.9851 - val_loss: 0.0724 - val_acc: 0.9848
Epoch 13/20

  32/2960 [..............................] - ETA: 0s - loss: 0.0867 - acc: 1.0000
 384/2960 [==>...........................] - ETA: 0s - loss: 0.0909 - acc: 0.9740
 576/2960 [====>.........................] - ETA: 0s - loss: 0.0871 - acc: 0.9792
 928/2960 [========>.....................] - ETA: 0s - loss: 0.0879 - acc: 0.9817
1504/2960 [==============>...............] - ETA: 0s - loss: 0.0888 - acc: 0.9827
2080/2960 [====================>.........] - ETA: 0s - loss: 0.0836 - acc: 0.9856
2336/2960 [======================>.......] - ETA: 0s - loss: 0.0826 - acc: 0.9863
2880/2960 [============================>.] - ETA: 0s - loss: 0.0807 - acc: 0.9875
2960/2960 [==============================] - 0s 134us/step - loss: 0.0816 - acc: 0.9872 - val_loss: 0.0699 - val_acc: 0.9848
Epoch 14/20

  32/2960 [..............................] - ETA: 0s - loss: 0.0764 - acc: 0.9688
 608/2960 [=====>........................] - ETA: 0s - loss: 0.0739 - acc: 0.9885
1184/2960 [===========>..................] - ETA: 0s - loss: 0.0807 - acc: 0.9865
1600/2960 [===============>..............] - ETA: 0s - loss: 0.0780 - acc: 0.9894
2016/2960 [===================>..........] - ETA: 0s - loss: 0.0736 - acc: 0.9916
2592/2960 [=========================>....] - ETA: 0s - loss: 0.0763 - acc: 0.9900
2960/2960 [==============================] - 0s 100us/step - loss: 0.0763 - acc: 0.9902 - val_loss: 0.0651 - val_acc: 0.9848
Epoch 15/20

  32/2960 [..............................] - ETA: 0s - loss: 0.0657 - acc: 1.0000
 448/2960 [===>..........................] - ETA: 0s - loss: 0.0772 - acc: 0.9911
 864/2960 [=======>......................] - ETA: 0s - loss: 0.0759 - acc: 0.9896
1312/2960 [============>.................] - ETA: 0s - loss: 0.0771 - acc: 0.9909
1824/2960 [=================>............] - ETA: 0s - loss: 0.0713 - acc: 0.9918
2304/2960 [======================>.......] - ETA: 0s - loss: 0.0689 - acc: 0.9913
2656/2960 [=========================>....] - ETA: 0s - loss: 0.0676 - acc: 0.9921
2960/2960 [==============================] - 0s 120us/step - loss: 0.0671 - acc: 0.9922 - val_loss: 0.0576 - val_acc: 0.9848
Epoch 16/20

  32/2960 [..............................] - ETA: 0s - loss: 0.0534 - acc: 1.0000
 512/2960 [====>.........................] - ETA: 0s - loss: 0.0768 - acc: 0.9863
1088/2960 [==========>...................] - ETA: 0s - loss: 0.0755 - acc: 0.9881
1536/2960 [==============>...............] - ETA: 0s - loss: 0.0706 - acc: 0.9902
1984/2960 [===================>..........] - ETA: 0s - loss: 0.0725 - acc: 0.9889
2400/2960 [=======================>......] - ETA: 0s - loss: 0.0713 - acc: 0.9892
2848/2960 [===========================>..] - ETA: 0s - loss: 0.0695 - acc: 0.9891
2960/2960 [==============================] - 0s 115us/step - loss: 0.0688 - acc: 0.9892 - val_loss: 0.0506 - val_acc: 0.9909
Epoch 17/20

  32/2960 [..............................] - ETA: 0s - loss: 0.0731 - acc: 1.0000
 256/2960 [=>............................] - ETA: 0s - loss: 0.0653 - acc: 0.9961
 576/2960 [====>.........................] - ETA: 0s - loss: 0.0565 - acc: 0.9948
 896/2960 [========>.....................] - ETA: 0s - loss: 0.0589 - acc: 0.9911
1312/2960 [============>.................] - ETA: 0s - loss: 0.0711 - acc: 0.9855
1856/2960 [=================>............] - ETA: 0s - loss: 0.0668 - acc: 0.9860
2240/2960 [=====================>........] - ETA: 0s - loss: 0.0662 - acc: 0.9862
2656/2960 [=========================>....] - ETA: 0s - loss: 0.0658 - acc: 0.9864
2960/2960 [==============================] - 0s 140us/step - loss: 0.0646 - acc: 0.9875 - val_loss: 0.0512 - val_acc: 0.9878
Epoch 18/20

  32/2960 [..............................] - ETA: 0s - loss: 0.0258 - acc: 1.0000
 672/2960 [=====>........................] - ETA: 0s - loss: 0.0524 - acc: 0.9911
1216/2960 [===========>..................] - ETA: 0s - loss: 0.0554 - acc: 0.9910
1664/2960 [===============>..............] - ETA: 0s - loss: 0.0576 - acc: 0.9904
2240/2960 [=====================>........] - ETA: 0s - loss: 0.0590 - acc: 0.9888
2912/2960 [============================>.] - ETA: 0s - loss: 0.0635 - acc: 0.9880
2960/2960 [==============================] - 0s 94us/step - loss: 0.0647 - acc: 0.9878 - val_loss: 0.0447 - val_acc: 0.9939
Epoch 19/20

  32/2960 [..............................] - ETA: 0s - loss: 0.0354 - acc: 1.0000
 480/2960 [===>..........................] - ETA: 0s - loss: 0.0509 - acc: 0.9958
 928/2960 [========>.....................] - ETA: 0s - loss: 0.0623 - acc: 0.9881
1472/2960 [=============>................] - ETA: 0s - loss: 0.0614 - acc: 0.9885
1984/2960 [===================>..........] - ETA: 0s - loss: 0.0594 - acc: 0.9889
2336/2960 [======================>.......] - ETA: 0s - loss: 0.0592 - acc: 0.9893
2688/2960 [==========================>...] - ETA: 0s - loss: 0.0590 - acc: 0.9896
2912/2960 [============================>.] - ETA: 0s - loss: 0.0604 - acc: 0.9894
2960/2960 [==============================] - 0s 149us/step - loss: 0.0602 - acc: 0.9895 - val_loss: 0.0434 - val_acc: 0.9878
Epoch 20/20

  32/2960 [..............................] - ETA: 0s - loss: 0.0393 - acc: 1.0000
 416/2960 [===>..........................] - ETA: 0s - loss: 0.0702 - acc: 0.9832
 768/2960 [======>.......................] - ETA: 0s - loss: 0.0632 - acc: 0.9870
1344/2960 [============>.................] - ETA: 0s - loss: 0.0577 - acc: 0.9888
1888/2960 [==================>...........] - ETA: 0s - loss: 0.0533 - acc: 0.9899
2464/2960 [=======================>......] - ETA: 0s - loss: 0.0515 - acc: 0.9911
2960/2960 [==============================] - 0s 118us/step - loss: 0.0513 - acc: 0.9916 - val_loss: 0.0416 - val_acc: 0.9878
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
dense_1 (Dense)              (None, 128)               4736      
_________________________________________________________________
batch_normalization_1 (Batch (None, 128)               512       
_________________________________________________________________
dense_2 (Dense)              (None, 64)                8256      
_________________________________________________________________
batch_normalization_2 (Batch (None, 64)                256       
_________________________________________________________________
dense_3 (Dense)              (None, 16)                1040      
_________________________________________________________________
batch_normalization_3 (Batch (None, 16)                64        
_________________________________________________________________
dense_4 (Dense)              (None, 4)                 68        
=================================================================
Total params: 14,932
Trainable params: 14,516
Non-trainable params: 416
_________________________________________________________________
Traceback (most recent call last):
  File "H:/Online-Realtime-Action-Recognition-based-on-OpenPose-master/Online-Realtime-Action-Recognition-based-on-OpenPose-master/Action/training/train.py", line 143, in <module>
    his.loss_plot('epoch')
  File "H:/Online-Realtime-Action-Recognition-based-on-OpenPose-master/Online-Realtime-Action-Recognition-based-on-OpenPose-master/Action/training/train.py", line 55, in loss_plot
    iters = range(len(self.losses[loss_type]))
AttributeError: 'LossHistory' object has no attribute 'losses'

Process finished with exit code 1

**Comment by liguangzi** [comment]
It seems that a solution has been found.
model.fit(X_train, Y_train, batch_size=32, epochs=20, verbose=1, validation_data=(X_test, Y_test))
change model.fit(X_train, Y_train, batch_size=32, epochs=20, verbose=1, validation_data=(X_test, Y_test), callbacks=[his])

But a new problem arises. How do I train a model? Can I train and save a new model by changing # model. save ('zyh_framewise_recognition.h5') to model. save ('zyh_framewise_recognition.h5')?

then Operation result:
Using TensorFlow backend.
Train on 2960 samples, validate on 329 samples
Epoch 1/20
2019-03-21 09:54:39.903078: I T:\src\github\tensorflow\tensorflow\core\platform\cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2

  32/2960 [..............................] - ETA: 4:42 - loss: 1.4157 - acc: 0.4062
 576/2960 [====>.........................] - ETA: 12s - loss: 1.3065 - acc: 0.4670 
1216/2960 [===========>..................] - ETA: 4s - loss: 1.1116 - acc: 0.5707 
1856/2960 [=================>............] - ETA: 1s - loss: 0.9642 - acc: 0.6466
2496/2960 [========================>.....] - ETA: 0s - loss: 0.8735 - acc: 0.6983
2960/2960 [==============================] - 3s 1ms/step - loss: 0.8225 - acc: 0.7270 - val_loss: 0.4968 - val_acc: 0.8997
Epoch 2/20

  32/2960 [..............................] - ETA: 0s - loss: 0.5554 - acc: 0.8438
 704/2960 [======>.......................] - ETA: 0s - loss: 0.4093 - acc: 0.9233
1280/2960 [===========>..................] - ETA: 0s - loss: 0.4068 - acc: 0.9219
1920/2960 [==================>...........] - ETA: 0s - loss: 0.4049 - acc: 0.9182
2560/2960 [========================>.....] - ETA: 0s - loss: 0.3928 - acc: 0.9168
2960/2960 [==============================] - 0s 84us/step - loss: 0.3837 - acc: 0.9186 - val_loss: 0.3299 - val_acc: 0.9301
Epoch 3/20

  32/2960 [..............................] - ETA: 0s - loss: 0.1623 - acc: 1.0000
 672/2960 [=====>........................] - ETA: 0s - loss: 0.2593 - acc: 0.9464
1184/2960 [===========>..................] - ETA: 0s - loss: 0.2703 - acc: 0.9476
1664/2960 [===============>..............] - ETA: 0s - loss: 0.2759 - acc: 0.9453
2208/2960 [=====================>........] - ETA: 0s - loss: 0.2662 - acc: 0.9488
2816/2960 [===========================>..] - ETA: 0s - loss: 0.2629 - acc: 0.9478
2960/2960 [==============================] - 0s 94us/step - loss: 0.2669 - acc: 0.9443 - val_loss: 0.2288 - val_acc: 0.9514
Epoch 4/20

  32/2960 [..............................] - ETA: 0s - loss: 0.1789 - acc: 0.9688
 544/2960 [====>.........................] - ETA: 0s - loss: 0.2082 - acc: 0.9651
 960/2960 [========>.....................] - ETA: 0s - loss: 0.2080 - acc: 0.9552
1440/2960 [=============>................] - ETA: 0s - loss: 0.1963 - acc: 0.9611
2048/2960 [===================>..........] - ETA: 0s - loss: 0.1879 - acc: 0.9658
2592/2960 [=========================>....] - ETA: 0s - loss: 0.1887 - acc: 0.9637
2960/2960 [==============================] - 0s 101us/step - loss: 0.1872 - acc: 0.9642 - val_loss: 0.1799 - val_acc: 0.9666
Epoch 5/20

  32/2960 [..............................] - ETA: 0s - loss: 0.1296 - acc: 1.0000
 640/2960 [=====>........................] - ETA: 0s - loss: 0.1565 - acc: 0.9766
1280/2960 [===========>..................] - ETA: 0s - loss: 0.1644 - acc: 0.9664
1920/2960 [==================>...........] - ETA: 0s - loss: 0.1617 - acc: 0.9677
2368/2960 [=======================>......] - ETA: 0s - loss: 0.1609 - acc: 0.9675
2944/2960 [============================>.] - ETA: 0s - loss: 0.1549 - acc: 0.9698
2960/2960 [==============================] - 0s 91us/step - loss: 0.1545 - acc: 0.9699 - val_loss: 0.1423 - val_acc: 0.9726
Epoch 6/20

  32/2960 [..............................] - ETA: 0s - loss: 0.0996 - acc: 1.0000
 672/2960 [=====>........................] - ETA: 0s - loss: 0.1209 - acc: 0.9866
1216/2960 [===========>..................] - ETA: 0s - loss: 0.1462 - acc: 0.9729
1664/2960 [===============>..............] - ETA: 0s - loss: 0.1402 - acc: 0.9748
2080/2960 [====================>.........] - ETA: 0s - loss: 0.1334 - acc: 0.9774
2528/2960 [========================>.....] - ETA: 0s - loss: 0.1294 - acc: 0.9778
2960/2960 [==============================] - 0s 104us/step - loss: 0.1264 - acc: 0.9780 - val_loss: 0.1260 - val_acc: 0.9848
Epoch 7/20

  32/2960 [..............................] - ETA: 0s - loss: 0.1184 - acc: 0.9688
 704/2960 [======>.......................] - ETA: 0s - loss: 0.1031 - acc: 0.9858
1248/2960 [===========>..................] - ETA: 0s - loss: 0.1031 - acc: 0.9840
1760/2960 [================>.............] - ETA: 0s - loss: 0.1048 - acc: 0.9841
2464/2960 [=======================>......] - ETA: 0s - loss: 0.1038 - acc: 0.9830
2960/2960 [==============================] - 0s 85us/step - loss: 0.1030 - acc: 0.9824 - val_loss: 0.1093 - val_acc: 0.9848
Epoch 8/20

  32/2960 [..............................] - ETA: 0s - loss: 0.0795 - acc: 1.0000
 448/2960 [===>..........................] - ETA: 0s - loss: 0.0888 - acc: 0.9844
 992/2960 [=========>....................] - ETA: 0s - loss: 0.1008 - acc: 0.9798
1600/2960 [===============>..............] - ETA: 0s - loss: 0.0888 - acc: 0.9862
2176/2960 [=====================>........] - ETA: 0s - loss: 0.0894 - acc: 0.9853
2848/2960 [===========================>..] - ETA: 0s - loss: 0.0915 - acc: 0.9849
2960/2960 [==============================] - 0s 93us/step - loss: 0.0916 - acc: 0.9848 - val_loss: 0.0984 - val_acc: 0.9848
Epoch 9/20

  32/2960 [..............................] - ETA: 0s - loss: 0.2358 - acc: 0.9688
 608/2960 [=====>........................] - ETA: 0s - loss: 0.0949 - acc: 0.9803
1248/2960 [===========>..................] - ETA: 0s - loss: 0.0956 - acc: 0.9808
1920/2960 [==================>...........] - ETA: 0s - loss: 0.0933 - acc: 0.9823
2560/2960 [========================>.....] - ETA: 0s - loss: 0.0938 - acc: 0.9801
2960/2960 [==============================] - 0s 88us/step - loss: 0.0927 - acc: 0.9801 - val_loss: 0.0849 - val_acc: 0.9848
Epoch 10/20

  32/2960 [..............................] - ETA: 0s - loss: 0.0822 - acc: 1.0000
 640/2960 [=====>........................] - ETA: 0s - loss: 0.0800 - acc: 0.9906
1248/2960 [===========>..................] - ETA: 0s - loss: 0.0778 - acc: 0.9904
1888/2960 [==================>...........] - ETA: 0s - loss: 0.0762 - acc: 0.9894
2368/2960 [=======================>......] - ETA: 0s - loss: 0.0771 - acc: 0.9869
2848/2960 [===========================>..] - ETA: 0s - loss: 0.0798 - acc: 0.9860
2960/2960 [==============================] - 0s 94us/step - loss: 0.0813 - acc: 0.9851 - val_loss: 0.0815 - val_acc: 0.9848
Epoch 11/20

  32/2960 [..............................] - ETA: 0s - loss: 0.0371 - acc: 1.0000
 704/2960 [======>.......................] - ETA: 0s - loss: 0.0689 - acc: 0.9886
1312/2960 [============>.................] - ETA: 0s - loss: 0.0714 - acc: 0.9893
1856/2960 [=================>............] - ETA: 0s - loss: 0.0704 - acc: 0.9892
2368/2960 [=======================>......] - ETA: 0s - loss: 0.0723 - acc: 0.9894
2944/2960 [============================>.] - ETA: 0s - loss: 0.0721 - acc: 0.9888
2960/2960 [==============================] - 0s 93us/step - loss: 0.0719 - acc: 0.9889 - val_loss: 0.0752 - val_acc: 0.9848
Epoch 12/20

  32/2960 [..............................] - ETA: 0s - loss: 0.0424 - acc: 1.0000
 448/2960 [===>..........................] - ETA: 0s - loss: 0.0554 - acc: 0.9911
 800/2960 [=======>......................] - ETA: 0s - loss: 0.0584 - acc: 0.9912
1216/2960 [===========>..................] - ETA: 0s - loss: 0.0598 - acc: 0.9893
1696/2960 [================>.............] - ETA: 0s - loss: 0.0642 - acc: 0.9888
2240/2960 [=====================>........] - ETA: 0s - loss: 0.0639 - acc: 0.9888
2784/2960 [===========================>..] - ETA: 0s - loss: 0.0654 - acc: 0.9889
2960/2960 [==============================] - 0s 116us/step - loss: 0.0648 - acc: 0.9895 - val_loss: 0.0696 - val_acc: 0.9939
Epoch 13/20

  32/2960 [..............................] - ETA: 0s - loss: 0.0731 - acc: 0.9688
 576/2960 [====>.........................] - ETA: 0s - loss: 0.0639 - acc: 0.9861
1088/2960 [==========>...................] - ETA: 0s - loss: 0.0597 - acc: 0.9908
1472/2960 [=============>................] - ETA: 0s - loss: 0.0573 - acc: 0.9918
1888/2960 [==================>...........] - ETA: 0s - loss: 0.0575 - acc: 0.9905
2208/2960 [=====================>........] - ETA: 0s - loss: 0.0570 - acc: 0.9909
2752/2960 [==========================>...] - ETA: 0s - loss: 0.0584 - acc: 0.9895
2960/2960 [==============================] - 0s 116us/step - loss: 0.0598 - acc: 0.9895 - val_loss: 0.0655 - val_acc: 0.9878
Epoch 14/20

  32/2960 [..............................] - ETA: 0s - loss: 0.0144 - acc: 1.0000
 544/2960 [====>.........................] - ETA: 0s - loss: 0.0579 - acc: 0.9926
1056/2960 [=========>....................] - ETA: 0s - loss: 0.0542 - acc: 0.9915
1632/2960 [===============>..............] - ETA: 0s - loss: 0.0595 - acc: 0.9890
2304/2960 [======================>.......] - ETA: 0s - loss: 0.0569 - acc: 0.9900
2944/2960 [============================>.] - ETA: 0s - loss: 0.0568 - acc: 0.9901
2960/2960 [==============================] - 0s 91us/step - loss: 0.0567 - acc: 0.9902 - val_loss: 0.0604 - val_acc: 0.9909
Epoch 15/20

  32/2960 [..............................] - ETA: 0s - loss: 0.0259 - acc: 1.0000
 640/2960 [=====>........................] - ETA: 0s - loss: 0.0525 - acc: 0.9922
1312/2960 [============>.................] - ETA: 0s - loss: 0.0578 - acc: 0.9886
2016/2960 [===================>..........] - ETA: 0s - loss: 0.0592 - acc: 0.9881
2624/2960 [=========================>....] - ETA: 0s - loss: 0.0600 - acc: 0.9863
2960/2960 [==============================] - 0s 86us/step - loss: 0.0581 - acc: 0.9875 - val_loss: 0.0591 - val_acc: 0.9939
Epoch 16/20

  32/2960 [..............................] - ETA: 0s - loss: 0.0714 - acc: 1.0000
 640/2960 [=====>........................] - ETA: 0s - loss: 0.0491 - acc: 0.9922
1344/2960 [============>.................] - ETA: 0s - loss: 0.0442 - acc: 0.9948
2016/2960 [===================>..........] - ETA: 0s - loss: 0.0457 - acc: 0.9940
2528/2960 [========================>.....] - ETA: 0s - loss: 0.0449 - acc: 0.9937
2960/2960 [==============================] - 0s 85us/step - loss: 0.0478 - acc: 0.9919 - val_loss: 0.0551 - val_acc: 0.9970
Epoch 17/20

  32/2960 [..............................] - ETA: 0s - loss: 0.0230 - acc: 1.0000
 672/2960 [=====>........................] - ETA: 0s - loss: 0.0509 - acc: 0.9911
1376/2960 [============>.................] - ETA: 0s - loss: 0.0527 - acc: 0.9906
1824/2960 [=================>............] - ETA: 0s - loss: 0.0536 - acc: 0.9896
2272/2960 [======================>.......] - ETA: 0s - loss: 0.0525 - acc: 0.9899
2816/2960 [===========================>..] - ETA: 0s - loss: 0.0524 - acc: 0.9904
2960/2960 [==============================] - 0s 94us/step - loss: 0.0523 - acc: 0.9902 - val_loss: 0.0541 - val_acc: 0.9939
Epoch 18/20

  32/2960 [..............................] - ETA: 0s - loss: 0.0228 - acc: 1.0000
 640/2960 [=====>........................] - ETA: 0s - loss: 0.0382 - acc: 0.9922
1184/2960 [===========>..................] - ETA: 0s - loss: 0.0413 - acc: 0.9932
1760/2960 [================>.............] - ETA: 0s - loss: 0.0385 - acc: 0.9949
2368/2960 [=======================>......] - ETA: 0s - loss: 0.0386 - acc: 0.9945
2960/2960 [==============================] - 0s 88us/step - loss: 0.0401 - acc: 0.9929 - val_loss: 0.0507 - val_acc: 0.9970
Epoch 19/20

  32/2960 [..............................] - ETA: 0s - loss: 0.0643 - acc: 0.9688
 672/2960 [=====>........................] - ETA: 0s - loss: 0.0407 - acc: 0.9911
1248/2960 [===========>..................] - ETA: 0s - loss: 0.0434 - acc: 0.9912
1824/2960 [=================>............] - ETA: 0s - loss: 0.0426 - acc: 0.9929
2464/2960 [=======================>......] - ETA: 0s - loss: 0.0391 - acc: 0.9939
2960/2960 [==============================] - 0s 85us/step - loss: 0.0407 - acc: 0.9929 - val_loss: 0.0476 - val_acc: 0.9970
Epoch 20/20

  32/2960 [..............................] - ETA: 0s - loss: 0.0233 - acc: 1.0000
 576/2960 [====>.........................] - ETA: 0s - loss: 0.0389 - acc: 0.9965
1152/2960 [==========>...................] - ETA: 0s - loss: 0.0380 - acc: 0.9948
1760/2960 [================>.............] - ETA: 0s - loss: 0.0353 - acc: 0.9955
2464/2960 [=======================>......] - ETA: 0s - loss: 0.0364 - acc: 0.9947
2960/2960 [==============================] - 0s 86us/step - loss: 0.0363 - acc: 0.9946 - val_loss: 0.0472 - val_acc: 0.9970
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
dense_1 (Dense)              (None, 128)               4736      
_________________________________________________________________
batch_normalization_1 (Batch (None, 128)               512       
_________________________________________________________________
dense_2 (Dense)              (None, 64)                8256      
_________________________________________________________________
batch_normalization_2 (Batch (None, 64)                256       
_________________________________________________________________
dense_3 (Dense)              (None, 16)                1040      
_________________________________________________________________
batch_normalization_3 (Batch (None, 16)                64        
_________________________________________________________________
dense_4 (Dense)              (None, 4)                 68        
=================================================================
Total params: 14,932
Trainable params: 14,516
Non-trainable params: 416
_________________________________________________________________

I can't see the progress of the program, but the Pycharm compiler shows that it's still running. Would you like to wait for it to run, and then automatically generate the save model. save ('zyh_framewise_recognition. h5') file?
