### ISSUE TITLE
can't find model

### ISSUE THREAD

**Issue by m3m3-chan** [LZQthePlane/Online-Realtime-Action-Recognition-based-on-OpenPose#17]
Hello,
Thanks for the great work on this repo!
I am trying to run the code on my Windows machine with Anaconda Python but I have 2 issues: 
   1. I can't download the **VGG tf-model** from the baidu website link nor does it download when using "./download" command! so I went to the mediafire links to download the VGG tf-model.
   2. now when I run "main.py" I get this error: 
```
Traceback (most recent call last):
  File "main.py", line 16, in <module>
    action_classifier = load_action_premodel('Action/framewise_recognition.h5')
  File "C:\Users\malabdou\Documents\Python\PyProj\Posture\10Online-Realtime-Action-Recognition-based-on-OpenPose-master\Action\recognizer.py", line 99, in load_action_premodel
    return load_model(model)
  File "C:\Users\malabdou\Anaconda3\envs\py5cv-33\lib\site-packages\keras\engine\saving.py", line 260, in load_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "C:\Users\malabdou\Anaconda3\envs\py5cv-33\lib\site-packages\keras\engine\saving.py", line 334, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "C:\Users\malabdou\Anaconda3\envs\py5cv-33\lib\site-packages\keras\layers\__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "C:\Users\malabdou\Anaconda3\envs\py5cv-33\lib\site-packages\keras\utils\generic_utils.py", line 145, in deserialize_keras_object
    list(custom_objects.items())))
  File "C:\Users\malabdou\Anaconda3\envs\py5cv-33\lib\site-packages\keras\engine\sequential.py", line 293, in from_config
    model.add(layer)
  File "C:\Users\malabdou\Anaconda3\envs\py5cv-33\lib\site-packages\keras\engine\sequential.py", line 185, in add
    output_tensor = layer(self.outputs[0])
  File "C:\Users\malabdou\Anaconda3\envs\py5cv-33\lib\site-packages\keras\engine\base_layer.py", line 457, in __call__
    output = self.call(inputs, **kwargs)
  File "C:\Users\malabdou\Anaconda3\envs\py5cv-33\lib\site-packages\keras\layers\core.py", line 878, in call
    output = self.activation(output)
  File "C:\Users\malabdou\Anaconda3\envs\py5cv-33\lib\site-packages\keras\activations.py", line 29, in softmax
    return K.softmax(x)
  File "C:\Users\malabdou\Anaconda3\envs\py5cv-33\lib\site-packages\keras\backend\tensorflow_backend.py", line 3154, in softmax
    return tf.nn.softmax(x, axis=axis)
TypeError: softmax() got an unexpected keyword argument 'axis'
```
Any way to solve this please?

**Comment by m3m3-chan** [comment]
problem solved!
I needed to upgrade tensorflow>=1.13 as softmax was introduced in later version in tf!
also the model from mediafire link seems to be working.
