### ISSUE TITLE
from tensorflow.python.keras.utils import tf_utils ImportError: cannot import name 'tf_utils'

### ISSUE THREAD

**Issue by FUZIRONG** [LZQthePlane/Online-Realtime-Action-Recognition-based-on-OpenPose#40]
run main.py,an error has occurred
Using TensorFlow backend.
Traceback (most recent call last):
  File "F:/action recognition demo/OPEN-POSE/Online-Realtime-Action-Recognition-based-on-OpenPose/main.py", line 8, in <module>
    from Action.recognizer import load_action_premodel, framewise_recognize
  File "F:\action recognition demo\OPEN-POSE\Online-Realtime-Action-Recognition-based-on-OpenPose\Action\recognizer.py", line 10, in <module>
    from keras.models import load_model
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\keras\__init__.py", line 3, in <module>
    from . import utils
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\keras\utils\__init__.py", line 6, in <module>
    from . import conv_utils
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\keras\utils\conv_utils.py", line 9, in <module>
    from .. import backend as K
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\keras\backend\__init__.py", line 1, in <module>
    from .load_backend import epsilon
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\keras\backend\load_backend.py", line 90, in <module>
    from .tensorflow_backend import *
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py", line 13, in <module>
    from tensorflow.python.keras.utils import tf_utils
ImportError: cannot import name 'tf_utils'

**Comment by saimj7** [comment]
@FUZIRONG what is your keras version? mine is 2.2.4 and it works fine

**Comment by FUZIRONG** [comment]
> @FUZIRONG what is your keras version? mine is 2.2.4 and it works fine

Thanks for the reply, it is caused by the problem of keras version

**Comment by thomas63360** [comment]
@FUZIRONG can you tell me which version of keras and which version of tensorflow do you use ?

**Comment by sunfeng90** [comment]
> @FUZIRONG can you tell me which version of keras and which version of tensorflow do you use ?

keras ==2.2.4
tensorflow-gpu==1.14.0

it works for me

**Comment by melon-coder** [comment]
> > @FUZIRONG can you tell me which version of keras and which version of tensorflow do you use ?
> 
> keras ==2.2.4
> tensorflow-gpu==1.14.0
> 
> it works for me

Can you give me a list of environment packages (including package name and version) for running this program?

**Comment by CandyMan7755** [comment]
2022-10-03 22:00:26.553326: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cudart64_101.dll
2022-10-03 22:00:33.309597: I tensorflow_io/core/kernels/cpu_check.cc:128] Your CPU supports instructions that this TensorFlow IO binary was not compiled to use: SSE SSE2 SSE3 SSE4.1 SSE4.2 AVX AVX2 FMA
Using TensorFlow backend.
D:\ANPR\anprsys\lib\site-packages\tensorflow_addons\utils\ensure_tf_install.py:67: UserWarning: Tensorflow Addons supports using Python ops for all Tensorflow versions above or equal to 2.8.0 and strictly below 2.11.0 (nightly versions are not supported). 
 The versions of TensorFlow you are currently using is 2.3.0 and is not supported. 
Some things might work, some things might not.
If you were to encounter a bug, do not file an issue.
If you want to make sure you're using a tested and supported configuration, either change the TensorFlow version or the TensorFlow Addons's version. 
You can find the compatibility matrix in TensorFlow Addon's readme:
https://github.com/tensorflow/addons
  UserWarning,
Traceback (most recent call last):
  File "D:\ANPR\anprsys\lib\site-packages\object_detection-0.1-py3.7.egg\object_detection\models\ssd_efficientnet_bifpn_feature_extractor.py", line 35, in <module>
    from official.legacy.image_classification.efficientnet import efficientnet_model
  File "D:\ANPR\anprsys\lib\site-packages\tf_models_official-2.10.0-py3.7.egg\official\legacy\image_classification\efficientnet\efficientnet_model.py", line 31, in <module>
    from official.legacy.image_classification import preprocessing
  File "D:\ANPR\anprsys\lib\site-packages\tf_models_official-2.10.0-py3.7.egg\official\legacy\image_classification\preprocessing.py", line 22, in <module>
    from official.legacy.image_classification import augment
  File "D:\ANPR\anprsys\lib\site-packages\tf_models_official-2.10.0-py3.7.egg\official\legacy\image_classification\augment.py", line 28, in <module>
    from keras.layers.preprocessing import image_preprocessing as image_ops
ModuleNotFoundError: No module named 'keras.layers.preprocessing'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Tensorflow\models\research\object_detection\builders\model_builder_tf2_test.py", line 24, in <module>
    from object_detection.builders import model_builder
  File "D:\ANPR\anprsys\lib\site-packages\object_detection-0.1-py3.7.egg\object_detection\builders\model_builder.py", line 70, in <module>
    from object_detection.models import ssd_efficientnet_bifpn_feature_extractor as ssd_efficientnet_bifpn
  File "D:\ANPR\anprsys\lib\site-packages\object_detection-0.1-py3.7.egg\object_detection\models\ssd_efficientnet_bifpn_feature_extractor.py", line 37, in <module>
    from official.vision.image_classification.efficientnet import efficientnet_model
  File "D:\ANPR\anprsys\lib\site-packages\tf_models_official-2.10.0-py3.7.egg\official\vision\__init__.py", line 17, in <module>
    from official.vision import configs
  File "D:\ANPR\anprsys\lib\site-packages\tf_models_official-2.10.0-py3.7.egg\official\vision\configs\__init__.py", line 19, in <module>
    from official.vision.configs import common
  File "D:\ANPR\anprsys\lib\site-packages\tf_models_official-2.10.0-py3.7.egg\official\vision\configs\common.py", line 22, in <module>
    from official.core import config_definitions as cfg
  File "D:\ANPR\anprsys\lib\site-packages\tf_models_official-2.10.0-py3.7.egg\official\core\__init__.py", line 17, in <module>
    from official.core import actions
  File "D:\ANPR\anprsys\lib\site-packages\tf_models_official-2.10.0-py3.7.egg\official\core\actions.py", line 25, in <module>
    from official.core import base_trainer
  File "D:\ANPR\anprsys\lib\site-packages\tf_models_official-2.10.0-py3.7.egg\official\core\base_trainer.py", line 28, in <module>
    from official.core import base_task
  File "D:\ANPR\anprsys\lib\site-packages\tf_models_official-2.10.0-py3.7.egg\official\core\base_task.py", line 23, in <module>
    from official.core import config_definitions
  File "D:\ANPR\anprsys\lib\site-packages\tf_models_official-2.10.0-py3.7.egg\official\core\config_definitions.py", line 21, in <module>
    from official.modeling.optimization.configs import optimization_config
  File "D:\ANPR\anprsys\lib\site-packages\tf_models_official-2.10.0-py3.7.egg\official\modeling\optimization\__init__.py", line 23, in <module>
    from official.modeling.optimization.optimizer_factory import OptimizerFactory
  File "D:\ANPR\anprsys\lib\site-packages\tf_models_official-2.10.0-py3.7.egg\official\modeling\optimization\optimizer_factory.py", line 20, in <module>
    import tensorflow_addons.optimizers as tfa_optimizers
  File "D:\ANPR\anprsys\lib\site-packages\tensorflow_addons\__init__.py", line 22, in <module>
    from tensorflow_addons import callbacks
  File "D:\ANPR\anprsys\lib\site-packages\tensorflow_addons\callbacks\__init__.py", line 17, in <module>
    from tensorflow_addons.callbacks.average_model_checkpoint import AverageModelCheckpoint
  File "D:\ANPR\anprsys\lib\site-packages\tensorflow_addons\callbacks\average_model_checkpoint.py", line 18, in <module>
    from tensorflow_addons.optimizers.average_wrapper import AveragedOptimizerWrapper
  File "D:\ANPR\anprsys\lib\site-packages\tensorflow_addons\optimizers\__init__.py", line 30, in <module>
    from tensorflow_addons.optimizers.discriminative_layer_training import (
  File "D:\ANPR\anprsys\lib\site-packages\tensorflow_addons\optimizers\discriminative_layer_training.py", line 25, in <module>
    from keras.utils import tf_utils
ImportError: cannot import name 'tf_utils' from 'keras.utils' (D:\ANPR\anprsys\lib\site-packages\keras\utils\__init__.py)

**Comment by alvinkimata** [comment]
I was able to resolve the error above by installing tensorflow addons with the tensorflow addons extension: 

```bash
pip install tensorflow==2.12 tensorflow-addons[tensorflow]
```

Note the tensorflow version I am using is version `2.12.0`
